# Generated by Django 3.2.4 on 2021-08-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_alter_review_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='site_url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
